### PR TITLE
now saving speed when storing a horse

### PR DESCRIPTION
**Pull request by Pasukaru**
Use https://dl.bukkit.org/downloads/craftbukkit/get/02389_1.6.4-R2.0/craftbukkit.jar as dependency instead of Bukkit.
If you want to support another version, you have to use the according CraftBukkit build.
This is a breaking change with every update, since there is no Bukkit API to read or modify an entity's speed.

### CODE REVIEW

**Comment by AsaAyers** [comment]
If I pull your patch into [my branch](https://github.com/AsaAyers/horsekeep) it breaks `mvn package`. Maybe you need to add something to the `pom.xml`?

```
...snip...
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 22 source files to /home/asa/horsekeep/HorseKeep/target/classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[7,35] package net.minecraft.server.v1_6_R3 does not exist

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[8,35] package net.minecraft.server.v1_6_R3 does not exist

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[17,44] package org.bukkit.craftbukkit.v1_6_R3.entity does not exist

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[357,166] cannot find symbol
symbol  : variable GenericAttributes
location: class main.java.com.gmail.falistos.HorseKeep.HorseManager

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[357,88] cannot find symbol
symbol  : class EntityInsentient
location: class main.java.com.gmail.falistos.HorseKeep.HorseManager

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[357,107] cannot find symbol
symbol  : class CraftLivingEntity
location: class main.java.com.gmail.falistos.HorseKeep.HorseManager

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[418,92] cannot find symbol
symbol  : variable GenericAttributes
location: class main.java.com.gmail.falistos.HorseKeep.HorseManager

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[418,7] cannot find symbol
symbol  : class EntityInsentient
location: class main.java.com.gmail.falistos.HorseKeep.HorseManager

/home/asa/horsekeep/HorseKeep/src/main/java/com/gmail/falistos/HorseKeep/HorseManager.java:[418,26] cannot find symbol
symbol  : class CraftLivingEntity
location: class main.java.com.gmail.falistos.HorseKeep.HorseManager

...snip...
```

**Comment by Pasukaru** [comment]
are you using CraftBukkit as dependency or Bukkit?
you have to use CraftBukkit for this to work

**Comment by AsaAyers** [comment]
I'm using `mvn package` since maven manages the dependencies.

**Comment by AsaAyers** [comment]
Java isn't my day to day language. Maven will pull in whatever dependencies you specify.

```
mvn --version
Apache Maven 2.2.1 (rdebian-10)
Java version: 1.6.0_31
Java home: /usr/lib/jvm/java-6-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.11.0-20-generic" arch: "amd64" Family: "unix"
```

**Comment by Pasukaru** [comment]
Mine neither and I havent worked with maven before, but what I can read from the pom.xml is that it uses Bukkit.
Need to change that to CraftBukkit somehow.

By the way, I used craftbukkit-1.6.4-R2.0  to compile it.
Depending on the version you want to support, you have to use the according CB build and adjust the imports. I haven't found a way to get a horse's speed with the bukkit api.

**Comment by AsaAyers** [comment]
That makes sense. I'm just recommending that since the project already has a `pom.xml` that does manage the dependencies it would be nice if your branch also updates `pom.xml` so it continues to work.

This compiled, but I don't have a development server setup right now to test anything. I also don't know exactly how this works, I just compiled it from some search results and your comment.

```
    <dependency>
         <groupId>org.bukkit</groupId>
         <artifactId>craftbukkit</artifactId>
      <version>1.6.4-R2.0</version>
    </dependency>
```

**Comment by Pasukaru** [comment]
will try that. thanks!

**Comment by falistos** [comment]
Hi,

I don't really like to deal with CraftBukkit directly (break every MC version), I am looking into this issue.

**Comment by Pasukaru** [comment]
I updated the pom.xml and also the code to work with 1.7.2-R2.

@britaniacraft 
I understand. However, the problem persists that the Bukkit API doesn't support entity manipulation of this kind (yet). 

Edit:
If working with CraftBukkit directly is no option for you, storing/retrieving horses from the virtual stable should be disabled IMHO - at least until there is a proper way of accessing the speed. Getting every horses speed set to 33 (without even knowing) is not acceptable.

**Comment by falistos** [comment]
I will work with reflection in order to not be mc version dependent

**Comment by Pasukaru** [comment]
I didnt think of that. Sounds good :+1:

**Comment by AsaAyers** [comment]
It looks like there's some kind of attribute system you could use. maybe? It's not clear to me exactly how this works or if it introduces any additional dependency.

https://github.com/ToastHelmi/HorseWhip/blob/master/HorseWhip/src/me/ToastHelmi/Entity/ToastHorse.java

**Comment by AsaAyers** [comment]
The [Attributes API](https://github.com/arfie/AttributesAPI/blob/master/AttributesAPI/src/nl/arfie/bukkit/attributes/wrapper/NBTTagList.java) plugin seems to load `net.minecraft.server` at runtime. Maybe because it changes with every version like CraftBukkit?

**Pull request closed without merging**
